-- =============================================
-- Seed: Ambiente Limpo / Produção
-- O sistema inicia sem credenciais padrão ou empresas demo.
-- O primeiro acesso deve ser realizado via Onboarding (/api/auth/registro).
-- =============================================
